name: rstools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - affine
  - build
  - dask
  - dask-geopandas
  - dask-image
  - fiona
  - geopandas
  - numba
  - numpy
  - pandas
  - pre-commit
  - pyarrow
  - pyogrio
  - pyproj
  - pytest
  - pytest-xdist
  - rasterio
  - rioxarray
  - scipy
  - shapely>=2
  - twine
  - xarray
